# Generated by Django 4.1.3 on 2022-11-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.FilePathField(path='/img')),
                ('syntax', models.TextField()),
                ('history', models.TextField()),
                ('rating_reasoning', models.TextField()),
                ('example', models.TextField()),
                ('rating', models.CharField(choices=[(1, 'Top Tier'), (2, 'Mid Tier'), (3, 'Low Tier')], max_length=1)),
            ],
        ),
    ]
